# Generated by Django 2.2 on 2020-05-27 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0022_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Заказы',
            },
        ),
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(choices=[(0, 'in_cart'), (1, 'ordered'), (2, 'paid'), (3, 'delivered'), (4, 'received')], max_length=1),
        ),
        migrations.AddField(
            model_name='deal',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mysite.Order', verbose_name='Заказ'),
        ),
    ]
