# Generated by Django 2.2 on 2020-05-27 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0023_auto_20200527_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mysite.Order', verbose_name='Заказ'),
        ),
    ]
