# Generated by Django 2.2 on 2020-05-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0024_auto_20200527_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(choices=[('0', 'in_cart'), ('1', 'ordered'), ('2', 'paid'), ('3', 'delivered'), ('4', 'received')], max_length=1),
        ),
    ]
