# Generated by Django 2.2 on 2020-05-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0025_auto_20200527_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='product_count',
            field=models.FloatField(blank=True, default=1, verbose_name='Количество'),
        ),
    ]
